/**
 * Seed knowledge base (F02 v0.3). It initialises an empty database and is the test fixture.
 *
 * C-18 / F02-AC-8.1 — nothing is invented: correction rules exist only for procedures the DPR
 * describes (Aadhaar, PAN, Voter ID). The other eight documents name their authority and carry
 * no rule, so the roadmap says "procedure not yet verified" for them. Nothing has a
 * last-verified date until the content team checks it on the official site (O03).
 * Kannada, Hindi and Urdu texts are draft translations awaiting review.
 */
import type { LocalizedText, Meta } from '../schema';
import type { KnowledgeBase } from './schema';

const DPR = 'DPR v1.0 §04 and §06 (as of Oct 2026) — re-verify on the official portal';
const meta = (owner: string, extra: Partial<Meta> = {}): Meta => ({
  owner,
  source: DPR,
  version: 1,
  lastVerified: null,
  status: 'in_review',
  ...extra,
});
const history = [{ version: 1, date: '2026-10-05', change: 'Seeded from DPR v1.0 §04 and §06', by: '1dentity build team' }];

const CONTENT = 'Content lead';
const FREE: LocalizedText = { en: 'Free', kn: 'ಉಚಿತ', hi: 'मुफ़्त', ur: 'مفت' };
const CENTRE_75: LocalizedText = { en: '₹75 at a centre', kn: 'ಕೇಂದ್ರದಲ್ಲಿ ₹75', hi: 'केंद्र पर ₹75', ur: 'مرکز پر ₹75' };
const VOTER_WHERE: LocalizedText = {
  en: "Voters' Service Portal or your Booth Level Officer (BLO)",
  kn: 'ಮತದಾರರ ಸೇವಾ ಪೋರ್ಟಲ್ ಅಥವಾ ನಿಮ್ಮ ಬೂತ್ ಮಟ್ಟದ ಅಧಿಕಾರಿ (BLO)',
  hi: 'मतदाता सेवा पोर्टल या आपके बूथ लेवल अधिकारी (BLO)',
  ur: 'ووٹرز سروس پورٹل یا آپ کا بوتھ لیول آفیسر (BLO)',
};
const REGISTER_NUMBER: LocalizedText = { en: 'Register number', kn: 'ರಿಜಿಸ್ಟರ್ ಸಂಖ್ಯೆ', hi: 'रजिस्टर नंबर', ur: 'رجسٹر نمبر' };
const CERTIFICATE_NUMBER: LocalizedText = { en: 'Certificate number', kn: 'ಪ್ರಮಾಣಪತ್ರ ಸಂಖ್ಯೆ', hi: 'प्रमाणपत्र संख्या', ur: 'سرٹیفکیٹ نمبر' };

export const seedKnowledgeBase: KnowledgeBase = {
  version: '2026.10.1-seed',
  jurisdictions: [
    { code: 'IN', name: { en: 'India', kn: 'ಭಾರತ', hi: 'भारत', ur: 'بھارت' } },
    { code: 'IN-KA', name: { en: 'Karnataka', kn: 'ಕರ್ನಾಟಕ', hi: 'कर्नाटक', ur: 'کرناٹک' } },
  ],
  authorities: [
    {
      id: 'uidai',
      name: {
        en: 'Unique Identification Authority of India (UIDAI)',
        kn: 'ಭಾರತೀಯ ವಿಶಿಷ್ಟ ಗುರುತು ಪ್ರಾಧಿಕಾರ (UIDAI)',
        hi: 'भारतीय विशिष्ट पहचान प्राधिकरण (UIDAI)',
        ur: 'یونیک آئیڈینٹیفکیشن اتھارٹی آف انڈیا (UIDAI)',
      },
      jurisdiction: 'IN',
      sources: ['uidai', 'myaadhaar'],
      meta: meta(CONTENT),
    },
    {
      id: 'income-tax',
      name: {
        en: 'Income Tax Department (PAN services through Protean and UTIITSL)',
        kn: 'ಆದಾಯ ತೆರಿಗೆ ಇಲಾಖೆ (Protean ಮತ್ತು UTIITSL ಮೂಲಕ ಪ್ಯಾನ್ ಸೇವೆಗಳು)',
        hi: 'आयकर विभाग (Protean और UTIITSL के ज़रिए पैन सेवाएँ)',
        ur: 'محکمہ انکم ٹیکس (Protean اور UTIITSL کے ذریعے پین خدمات)',
      },
      jurisdiction: 'IN',
      sources: ['protean', 'utiitsl'],
      meta: meta(CONTENT),
    },
    {
      id: 'passport-seva',
      name: { en: 'Ministry of External Affairs — Passport Seva', kn: 'ವಿದೇಶಾಂಗ ವ್ಯವಹಾರಗಳ ಸಚಿವಾಲಯ — ಪಾಸ್‌ಪೋರ್ಟ್ ಸೇವಾ', hi: 'विदेश मंत्रालय — पासपोर्ट सेवा', ur: 'وزارتِ خارجہ — پاسپورٹ سیوا' },
      jurisdiction: 'IN',
      sources: [],
      meta: meta(CONTENT),
    },
    {
      id: 'eci',
      name: { en: 'Election Commission of India', kn: 'ಭಾರತ ಚುನಾವಣಾ ಆಯೋಗ', hi: 'भारत निर्वाचन आयोग', ur: 'الیکشن کمیشن آف انڈیا' },
      jurisdiction: 'IN',
      sources: ['voters-service-portal'],
      meta: meta(CONTENT),
    },
    {
      id: 'ka-transport',
      name: { en: 'Transport Department, Karnataka (Parivahan Sarathi)', kn: 'ಸಾರಿಗೆ ಇಲಾಖೆ, ಕರ್ನಾಟಕ (ಪರಿವಹನ್ ಸಾರಥಿ)', hi: 'परिवहन विभाग, कर्नाटक (परिवहन सारथी)', ur: 'محکمہ ٹرانسپورٹ، کرناٹک (پریوہن سارتھی)' },
      jurisdiction: 'IN-KA',
      sources: [],
      meta: meta(CONTENT),
    },
    {
      id: 'ka-registrar-births',
      name: {
        en: 'Registrar of Births and Deaths (local body), Karnataka — Civil Registration System',
        kn: 'ಜನನ ಮತ್ತು ಮರಣ ನೋಂದಣಾಧಿಕಾರಿ (ಸ್ಥಳೀಯ ಸಂಸ್ಥೆ), ಕರ್ನಾಟಕ — ನಾಗರಿಕ ನೋಂದಣಿ ವ್ಯವಸ್ಥೆ',
        hi: 'जन्म और मृत्यु रजिस्ट्रार (स्थानीय निकाय), कर्नाटक — नागरिक पंजीकरण प्रणाली',
        ur: 'رجسٹرار برائے پیدائش و اموات (مقامی ادارہ)، کرناٹک — سول رجسٹریشن سسٹم',
      },
      jurisdiction: 'IN-KA',
      sources: [],
      meta: meta(CONTENT),
    },
    {
      id: 'ka-exam-board',
      name: {
        en: 'Karnataka School Examination and Assessment Board (KSEAB)',
        kn: 'ಕರ್ನಾಟಕ ಶಾಲಾ ಪರೀಕ್ಷೆ ಮತ್ತು ಮೌಲ್ಯನಿರ್ಣಯ ಮಂಡಳಿ (KSEAB)',
        hi: 'कर्नाटक स्कूल परीक्षा और मूल्यांकन बोर्ड (KSEAB)',
        ur: 'کرناٹک اسکول امتحانات و تشخیص بورڈ (KSEAB)',
      },
      jurisdiction: 'IN-KA',
      sources: [],
      meta: meta(CONTENT, { source: 'Not in the DPR — authority name to be verified by the content lead (O03)' }),
    },
    {
      id: 'ka-revenue',
      name: { en: 'Revenue Department, Karnataka — Nadakacheri / Seva Sindhu', kn: 'ಕಂದಾಯ ಇಲಾಖೆ, ಕರ್ನಾಟಕ — ನಾಡಕಚೇರಿ / ಸೇವಾ ಸಿಂಧು', hi: 'राजस्व विभाग, कर्नाटक — नाडकचेरी / सेवा सिंधु', ur: 'محکمہ مال، کرناٹک — نادکچیری / سیوا سندھو' },
      jurisdiction: 'IN-KA',
      sources: [],
      meta: meta(CONTENT),
    },
    {
      id: 'ka-food',
      name: {
        en: 'Food, Civil Supplies and Consumer Affairs Department, Karnataka',
        kn: 'ಆಹಾರ, ನಾಗರಿಕ ಸರಬರಾಜು ಮತ್ತು ಗ್ರಾಹಕ ವ್ಯವಹಾರಗಳ ಇಲಾಖೆ, ಕರ್ನಾಟಕ',
        hi: 'खाद्य, नागरिक आपूर्ति और उपभोक्ता मामले विभाग, कर्नाटक',
        ur: 'محکمہ خوراک، شہری رسد و امورِ صارفین، کرناٹک',
      },
      jurisdiction: 'IN-KA',
      sources: [],
      meta: meta(CONTENT),
    },
  ],
  sources: [
    { id: 'myaadhaar', title: { en: 'myAadhaar portal', kn: 'myAadhaar ಪೋರ್ಟಲ್', hi: 'myAadhaar पोर्टल', ur: 'myAadhaar پورٹل' }, url: 'https://myaadhaar.uidai.gov.in/', authority: 'uidai', kind: 'portal', meta: meta(CONTENT) },
    {
      id: 'uidai',
      title: { en: 'UIDAI website — Aadhaar centres', kn: 'UIDAI ವೆಬ್‌ಸೈಟ್ — ಆಧಾರ್ ಕೇಂದ್ರಗಳು', hi: 'UIDAI वेबसाइट — आधार केंद्र', ur: 'UIDAI ویب سائٹ — آدھار مراکز' },
      url: 'https://uidai.gov.in/',
      authority: 'uidai',
      kind: 'portal',
      meta: meta(CONTENT),
    },
    { id: 'protean', title: { en: 'Protean — PAN services', kn: 'Protean — ಪ್ಯಾನ್ ಸೇವೆಗಳು', hi: 'Protean — पैन सेवाएँ', ur: 'Protean — پین خدمات' }, url: 'https://www.protean-tinpan.com/', authority: 'income-tax', kind: 'portal', meta: meta(CONTENT) },
    { id: 'utiitsl', title: { en: 'UTIITSL — PAN services', kn: 'UTIITSL — ಪ್ಯಾನ್ ಸೇವೆಗಳು', hi: 'UTIITSL — पैन सेवाएँ', ur: 'UTIITSL — پین خدمات' }, url: 'https://www.pan.utiitsl.com/', authority: 'income-tax', kind: 'portal', meta: meta(CONTENT) },
    {
      id: 'voters-service-portal',
      title: { en: "Voters' Service Portal", kn: 'ಮತದಾರರ ಸೇವಾ ಪೋರ್ಟಲ್', hi: 'मतदाता सेवा पोर्टल', ur: 'ووٹرز سروس پورٹل' },
      url: 'https://voters.eci.gov.in/',
      authority: 'eci',
      kind: 'portal',
      meta: meta(CONTENT),
    },
  ],
  catalogue: [
    {
      kind: 'aadhaar',
      label: { en: 'Aadhaar', kn: 'ಆಧಾರ್', hi: 'आधार', ur: 'آدھار' },
      tier: 3,
      fields: [{ field: 'name', optional: false }, { field: 'dob', optional: false }, { field: 'gender', optional: false }, { field: 'address', optional: false }],
      numberLabel: { en: 'Aadhaar number — we keep only the last 4 digits', kn: 'ಆಧಾರ್ ಸಂಖ್ಯೆ — ನಾವು ಕೊನೆಯ 4 ಅಂಕಿಗಳನ್ನು ಮಾತ್ರ ಇಡುತ್ತೇವೆ', hi: 'आधार नंबर — हम केवल आख़िरी 4 अंक रखते हैं', ur: 'آدھار نمبر — ہم صرف آخری 4 ہندسے رکھتے ہیں' },
      numberStorage: 'last4_only',
      authorities: [{ jurisdiction: 'IN', authority: 'uidai' }],
    },
    {
      kind: 'pan',
      label: { en: 'PAN', kn: 'ಪ್ಯಾನ್', hi: 'पैन', ur: 'پین' },
      tier: 3,
      fields: [{ field: 'name', optional: false }, { field: 'father_name', optional: false }, { field: 'dob', optional: false }],
      numberLabel: { en: 'PAN', kn: 'ಪ್ಯಾನ್ ಸಂಖ್ಯೆ', hi: 'पैन नंबर', ur: 'پین نمبر' },
      numberStorage: 'encrypted',
      authorities: [{ jurisdiction: 'IN', authority: 'income-tax' }],
    },
    {
      kind: 'passport',
      label: { en: 'Passport', kn: 'ಪಾಸ್‌ಪೋರ್ಟ್', hi: 'पासपोर्ट', ur: 'پاسپورٹ' },
      tier: 4,
      fields: [
        { field: 'name', optional: false },
        { field: 'dob', optional: false },
        { field: 'gender', optional: false },
        { field: 'place_of_birth', optional: false },
        { field: 'father_name', optional: false },
        { field: 'mother_name', optional: false },
        { field: 'spouse_name', optional: true },
        { field: 'address', optional: true },
      ],
      numberLabel: { en: 'Passport number', kn: 'ಪಾಸ್‌ಪೋರ್ಟ್ ಸಂಖ್ಯೆ', hi: 'पासपोर्ट नंबर', ur: 'پاسپورٹ نمبر' },
      numberStorage: 'encrypted',
      authorities: [{ jurisdiction: 'IN', authority: 'passport-seva' }],
    },
    {
      kind: 'voter_id',
      label: { en: 'Voter ID (EPIC)', kn: 'ಮತದಾರರ ಗುರುತಿನ ಚೀಟಿ (EPIC)', hi: 'मतदाता पहचान पत्र (EPIC)', ur: 'ووٹر آئی ڈی (EPIC)' },
      tier: 4,
      fields: [{ field: 'name', optional: false }, { field: 'relative_name', optional: false }, { field: 'gender', optional: false }, { field: 'dob', optional: true }, { field: 'address', optional: false }],
      numberLabel: { en: 'EPIC number', kn: 'EPIC ಸಂಖ್ಯೆ', hi: 'EPIC नंबर', ur: 'EPIC نمبر' },
      numberStorage: 'encrypted',
      authorities: [{ jurisdiction: 'IN', authority: 'eci' }],
    },
    {
      kind: 'driving_licence',
      label: { en: 'Driving licence', kn: 'ಚಾಲನಾ ಪರವಾನಗಿ', hi: 'ड्राइविंग लाइसेंस', ur: 'ڈرائیونگ لائسنس' },
      tier: 4,
      fields: [{ field: 'name', optional: false }, { field: 'relative_name', optional: true }, { field: 'dob', optional: false }, { field: 'address', optional: false }],
      numberLabel: { en: 'Licence number', kn: 'ಪರವಾನಗಿ ಸಂಖ್ಯೆ', hi: 'लाइसेंस नंबर', ur: 'لائسنس نمبر' },
      numberStorage: 'encrypted',
      authorities: [{ jurisdiction: 'IN-KA', authority: 'ka-transport' }],
    },
    {
      kind: 'birth_certificate',
      label: { en: 'Birth certificate', kn: 'ಜನನ ಪ್ರಮಾಣಪತ್ರ', hi: 'जन्म प्रमाणपत्र', ur: 'پیدائش کا سرٹیفکیٹ' },
      tier: 1,
      fields: [
        { field: 'name', optional: true },
        { field: 'dob', optional: false },
        { field: 'gender', optional: false },
        { field: 'place_of_birth', optional: false },
        { field: 'father_name', optional: false },
        { field: 'mother_name', optional: false },
        { field: 'address', optional: true },
      ],
      numberLabel: { en: 'Registration number', kn: 'ನೋಂದಣಿ ಸಂಖ್ಯೆ', hi: 'पंजीकरण संख्या', ur: 'رجسٹریشن نمبر' },
      numberStorage: 'encrypted',
      authorities: [{ jurisdiction: 'IN-KA', authority: 'ka-registrar-births' }],
    },
    {
      kind: 'sslc',
      label: { en: 'SSLC / 10th marks card', kn: 'ಎಸ್‌ಎಸ್‌ಎಲ್‌ಸಿ / 10ನೇ ತರಗತಿ ಅಂಕಪಟ್ಟಿ', hi: 'SSLC / 10वीं की अंकसूची', ur: 'SSLC / دسویں کا مارکس کارڈ' },
      tier: 2,
      fields: [{ field: 'name', optional: false }, { field: 'dob', optional: false }, { field: 'father_name', optional: false }, { field: 'mother_name', optional: false }],
      numberLabel: REGISTER_NUMBER,
      numberStorage: 'encrypted',
      authorities: [{ jurisdiction: 'IN-KA', authority: 'ka-exam-board' }],
    },
    {
      kind: 'puc',
      label: { en: 'PUC / 12th marks card', kn: 'ಪಿಯುಸಿ / 12ನೇ ತರಗತಿ ಅಂಕಪಟ್ಟಿ', hi: 'PUC / 12वीं की अंकसूची', ur: 'PUC / بارہویں کا مارکس کارڈ' },
      tier: 2,
      fields: [{ field: 'name', optional: false }, { field: 'dob', optional: true }, { field: 'father_name', optional: true }, { field: 'mother_name', optional: true }],
      numberLabel: REGISTER_NUMBER,
      numberStorage: 'encrypted',
      authorities: [{ jurisdiction: 'IN-KA', authority: 'ka-exam-board' }],
    },
    {
      kind: 'caste_certificate',
      label: { en: 'Caste certificate', kn: 'ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ', hi: 'जाति प्रमाणपत्र', ur: 'ذات کا سرٹیفکیٹ' },
      tier: 5,
      fields: [{ field: 'name', optional: false }, { field: 'relative_name', optional: false }, { field: 'address', optional: false }],
      numberLabel: CERTIFICATE_NUMBER,
      numberStorage: 'encrypted',
      authorities: [{ jurisdiction: 'IN-KA', authority: 'ka-revenue' }],
    },
    {
      kind: 'income_certificate',
      label: { en: 'Income certificate', kn: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ', hi: 'आय प्रमाणपत्र', ur: 'آمدنی کا سرٹیفکیٹ' },
      tier: 5,
      fields: [{ field: 'name', optional: false }, { field: 'relative_name', optional: false }, { field: 'address', optional: false }],
      numberLabel: CERTIFICATE_NUMBER,
      numberStorage: 'encrypted',
      authorities: [{ jurisdiction: 'IN-KA', authority: 'ka-revenue' }],
    },
    {
      kind: 'ration_card',
      label: { en: 'Ration card', kn: 'ಪಡಿತರ ಚೀಟಿ', hi: 'राशन कार्ड', ur: 'راشن کارڈ' },
      tier: 5,
      fields: [{ field: 'name', optional: false }, { field: 'address', optional: false }],
      numberLabel: { en: 'Ration card number', kn: 'ಪಡಿತರ ಚೀಟಿ ಸಂಖ್ಯೆ', hi: 'राशन कार्ड नंबर', ur: 'راشن کارڈ نمبر' },
      numberStorage: 'encrypted',
      authorities: [{ jurisdiction: 'IN-KA', authority: 'ka-food' }],
    },
  ],
  rules: [
    {
      id: 'aadhaar-demographic-update',
      document: 'aadhaar',
      jurisdiction: 'IN',
      authority: 'uidai',
      fields: ['name', 'dob', 'gender', 'address'],
      issueTypes: ['spelling', 'name_change', 'date', 'gender', 'address'],
      category: 'update',
      evidence: [
        {
          en: 'Proof of the correct detail — for date of birth, a birth certificate or SSLC marks card',
          kn: 'ಸರಿಯಾದ ವಿವರದ ಪುರಾವೆ — ಜನ್ಮ ದಿನಾಂಕಕ್ಕೆ ಜನನ ಪ್ರಮಾಣಪತ್ರ ಅಥವಾ SSLC ಅಂಕಪಟ್ಟಿ',
          hi: 'सही विवरण का प्रमाण — जन्मतिथि के लिए जन्म प्रमाणपत्र या SSLC अंकपत्र',
          ur: 'درست تفصیل کا ثبوت — تاریخ پیدائش کے لیے پیدائش کا سرٹیفکیٹ یا SSLC مارکس کارڈ',
        },
      ],
      requiredDocuments: [{ en: 'Your Aadhaar card', kn: 'ನಿಮ್ಮ ಆಧಾರ್ ಕಾರ್ಡ್', hi: 'आपका आधार कार्ड', ur: 'آپ کا آدھار کارڈ' }],
      prerequisites: [],
      route: {
        mode: 'both',
        where: { en: 'Aadhaar centre, or myAadhaar for address', kn: 'ಆಧಾರ್ ಕೇಂದ್ರ, ಅಥವಾ ವಿಳಾಸಕ್ಕೆ myAadhaar', hi: 'आधार केंद्र, या पते के लिए myAadhaar', ur: 'آدھار مرکز، یا پتے کے لیے myAadhaar' },
      },
      steps: [
        {
          en: 'Visit an Aadhaar enrolment and update centre with your Aadhaar card and proof of the correct detail.',
          kn: 'ನಿಮ್ಮ ಆಧಾರ್ ಕಾರ್ಡ್ ಮತ್ತು ಸರಿಯಾದ ವಿವರದ ಪುರಾವೆಯೊಂದಿಗೆ ಆಧಾರ್ ನೋಂದಣಿ ಮತ್ತು ನವೀಕರಣ ಕೇಂದ್ರಕ್ಕೆ ಭೇಟಿ ನೀಡಿ.',
          hi: 'अपना आधार कार्ड और सही विवरण का प्रमाण लेकर आधार नामांकन और अपडेट केंद्र जाएँ।',
          ur: 'اپنا آدھار کارڈ اور درست تفصیل کا ثبوت لے کر آدھار اندراج اور اپڈیٹ مرکز جائیں۔',
        },
        {
          en: 'For an address change, you can also apply online on the myAadhaar portal.',
          kn: 'ವಿಳಾಸ ಬದಲಾವಣೆಗೆ myAadhaar ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಆನ್‌ಲೈನ್‌ನಲ್ಲೂ ಅರ್ಜಿ ಸಲ್ಲಿಸಬಹುದು.',
          hi: 'पता बदलने के लिए आप myAadhaar पोर्टल पर ऑनलाइन भी आवेदन कर सकते हैं।',
          ur: 'پتہ بدلنے کے لیے آپ myAadhaar پورٹل پر آن لائن بھی درخواست دے سکتے ہیں۔',
        },
      ],
      fees: [{ id: 'aadhaar-demographic-update-centre-fee', label: CENTRE_75, amountInr: 75, meta: meta(CONTENT) }],
      sources: ['uidai', 'myaadhaar'],
      priority: 20,
      history,
      meta: meta(CONTENT),
    },
    {
      id: 'pan-name-dob-correction',
      document: 'pan',
      jurisdiction: 'IN',
      authority: 'income-tax',
      fields: ['name', 'dob', 'father_name'],
      issueTypes: ['spelling', 'name_change', 'date', 'relation'],
      category: 'update',
      evidence: [
        {
          en: 'Proof of the correct detail — after marriage, a marriage certificate',
          kn: 'ಸರಿಯಾದ ವಿವರದ ಪುರಾವೆ — ಮದುವೆಯ ನಂತರ, ವಿವಾಹ ಪ್ರಮಾಣಪತ್ರ',
          hi: 'सही विवरण का प्रमाण — शादी के बाद, विवाह प्रमाणपत्र',
          ur: 'درست تفصیل کا ثبوت — شادی کے بعد، شادی کا سرٹیفکیٹ',
        },
      ],
      requiredDocuments: [
        { en: 'Your PAN card', kn: 'ನಿಮ್ಮ ಪ್ಯಾನ್ ಕಾರ್ಡ್', hi: 'आपका पैन कार्ड', ur: 'آپ کا پین کارڈ' },
        { en: 'Your Aadhaar — PAN details must match it', kn: 'ನಿಮ್ಮ ಆಧಾರ್ — ಪ್ಯಾನ್ ವಿವರಗಳು ಅದಕ್ಕೆ ಹೊಂದಬೇಕು', hi: 'आपका आधार — पैन के विवरण इससे मेल खाने चाहिए', ur: 'آپ کا آدھار — پین کی تفصیلات اس سے ملنی چاہئیں' },
      ],
      prerequisites: [
        {
          document: 'aadhaar',
          fields: ['name', 'dob'],
          reason: {
            en: 'PAN–Aadhaar linking fails when the name or date of birth differ, so Aadhaar must be right first.',
            kn: 'ಹೆಸರು ಅಥವಾ ಜನ್ಮ ದಿನಾಂಕ ಬೇರೆಯಾಗಿದ್ದರೆ ಪ್ಯಾನ್–ಆಧಾರ್ ಲಿಂಕ್ ವಿಫಲವಾಗುತ್ತದೆ, ಆದ್ದರಿಂದ ಮೊದಲು ಆಧಾರ್ ಸರಿಯಾಗಿರಬೇಕು.',
            hi: 'नाम या जन्मतिथि अलग होने पर पैन–आधार लिंकिंग विफल होती है, इसलिए पहले आधार सही होना चाहिए।',
            ur: 'نام یا تاریخ پیدائش مختلف ہو تو پین–آدھار لنکنگ ناکام ہوتی ہے، اس لیے پہلے آدھار درست ہونا چاہیے۔',
          },
        },
      ],
      route: {
        mode: 'both',
        form: 'PAN CR-01',
        where: { en: 'Protean or UTIITSL — online or at a PAN centre', kn: 'Protean ಅಥವಾ UTIITSL — ಆನ್‌ಲೈನ್ ಅಥವಾ ಪ್ಯಾನ್ ಕೇಂದ್ರದಲ್ಲಿ', hi: 'Protean या UTIITSL — ऑनलाइन या पैन केंद्र पर', ur: 'Protean یا UTIITSL — آن لائن یا پین مرکز پر' },
      },
      steps: [
        {
          en: 'Apply with Form PAN CR-01 through Protean or UTIITSL, online or at a PAN centre.',
          kn: 'Protean ಅಥವಾ UTIITSL ಮೂಲಕ, ಆನ್‌ಲೈನ್ ಅಥವಾ ಪ್ಯಾನ್ ಕೇಂದ್ರದಲ್ಲಿ, ಫಾರ್ಮ್ PAN CR-01 ನೊಂದಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
          hi: 'Protean या UTIITSL के ज़रिए, ऑनलाइन या पैन केंद्र पर, फ़ॉर्म PAN CR-01 से आवेदन करें।',
          ur: 'Protean یا UTIITSL کے ذریعے، آن لائن یا پین مرکز پر، فارم PAN CR-01 سے درخواست دیں۔',
        },
      ],
      tracking: {
        en: 'Keep your acknowledgement and track the application until the new PAN arrives.',
        kn: 'ನಿಮ್ಮ ಸ್ವೀಕೃತಿಯನ್ನು ಇಟ್ಟುಕೊಳ್ಳಿ ಮತ್ತು ಹೊಸ ಪ್ಯಾನ್ ಬರುವವರೆಗೆ ಅರ್ಜಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
        hi: 'अपनी पावती रखें और नया पैन आने तक आवेदन ट्रैक करें।',
        ur: 'اپنی رسید رکھیں اور نیا پین آنے تک درخواست ٹریک کریں۔',
      },
      fees: [
        {
          id: 'pan-cr-01-fee',
          label: {
            en: 'About ₹101–107 with a physical card; less for e-PAN only',
            kn: 'ಭೌತಿಕ ಕಾರ್ಡ್‌ನೊಂದಿಗೆ ಸುಮಾರು ₹101–107; ಇ-ಪ್ಯಾನ್ ಮಾತ್ರಕ್ಕೆ ಕಡಿಮೆ',
            hi: 'फ़िज़िकल कार्ड के साथ लगभग ₹101–107; सिर्फ़ ई-पैन के लिए कम',
            ur: 'فزیکل کارڈ کے ساتھ تقریباً ₹101–107؛ صرف ای-پین کے لیے کم',
          },
          meta: meta(CONTENT, { effectiveFrom: '2026-04-01' }),
        },
      ],
      sources: ['protean', 'utiitsl'],
      priority: 30,
      history,
      meta: meta(CONTENT),
    },
    {
      id: 'voter-form-8-correction',
      document: 'voter_id',
      jurisdiction: 'IN',
      authority: 'eci',
      fields: ['name', 'dob', 'gender', 'relative_name', 'father_name', 'mother_name', 'spouse_name'],
      issueTypes: ['spelling', 'name_change', 'date', 'gender', 'relation'],
      category: 'update',
      evidence: [],
      requiredDocuments: [{ en: 'Your Voter ID (EPIC)', kn: 'ನಿಮ್ಮ ಮತದಾರರ ಗುರುತಿನ ಚೀಟಿ (EPIC)', hi: 'आपका मतदाता पहचान पत्र (EPIC)', ur: 'آپ کا ووٹر آئی ڈی (EPIC)' }],
      prerequisites: [],
      route: { mode: 'both', form: 'Form 8', where: VOTER_WHERE },
      steps: [
        {
          en: "Apply with Form 8 (correction of entries) on the Voters' Service Portal, or through your Booth Level Officer (BLO).",
          kn: 'ಮತದಾರರ ಸೇವಾ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅಥವಾ ನಿಮ್ಮ ಬೂತ್ ಮಟ್ಟದ ಅಧಿಕಾರಿ (BLO) ಮೂಲಕ ಫಾರ್ಮ್ 8 (ವಿವರಗಳ ತಿದ್ದುಪಡಿ) ನೊಂದಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
          hi: 'मतदाता सेवा पोर्टल पर या अपने बूथ लेवल अधिकारी (BLO) के ज़रिए फ़ॉर्म 8 (प्रविष्टियों में सुधार) से आवेदन करें।',
          ur: 'ووٹرز سروس پورٹل پر یا اپنے بوتھ لیول آفیسر (BLO) کے ذریعے فارم 8 (اندراجات کی درستی) سے درخواست دیں۔',
        },
      ],
      fees: [{ id: 'voter-form-8-correction-fee', label: FREE, amountInr: 0, meta: meta(CONTENT) }],
      sources: ['voters-service-portal'],
      priority: 40,
      history,
      meta: meta(CONTENT),
    },
    {
      id: 'voter-form-8-shifting',
      document: 'voter_id',
      jurisdiction: 'IN',
      authority: 'eci',
      fields: ['address'],
      issueTypes: ['address'],
      category: 'update',
      evidence: [],
      requiredDocuments: [{ en: 'Your Voter ID (EPIC)', kn: 'ನಿಮ್ಮ ಮತದಾರರ ಗುರುತಿನ ಚೀಟಿ (EPIC)', hi: 'आपका मतदाता पहचान पत्र (EPIC)', ur: 'آپ کا ووٹر آئی ڈی (EPIC)' }],
      prerequisites: [
        {
          document: 'aadhaar',
          fields: ['address'],
          reason: {
            en: 'Update the address on Aadhaar first, then on your Voter ID.',
            kn: 'ಮೊದಲು ಆಧಾರ್‌ನಲ್ಲಿ ವಿಳಾಸ ನವೀಕರಿಸಿ, ನಂತರ ಮತದಾರರ ಗುರುತಿನ ಚೀಟಿಯಲ್ಲಿ.',
            hi: 'पहले आधार पर पता अपडेट करें, फिर मतदाता पहचान पत्र पर।',
            ur: 'پہلے آدھار پر پتہ اپڈیٹ کریں، پھر ووٹر آئی ڈی پر۔',
          },
        },
      ],
      route: { mode: 'both', form: 'Form 8', where: VOTER_WHERE },
      steps: [
        {
          en: "Apply with Form 8 (shifting of residence) on the Voters' Service Portal, or through your BLO.",
          kn: 'ಮತದಾರರ ಸೇವಾ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅಥವಾ ನಿಮ್ಮ BLO ಮೂಲಕ ಫಾರ್ಮ್ 8 (ವಾಸಸ್ಥಳ ಬದಲಾವಣೆ) ನೊಂದಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.',
          hi: 'मतदाता सेवा पोर्टल पर या अपने BLO के ज़रिए फ़ॉर्म 8 (निवास स्थानांतरण) से आवेदन करें।',
          ur: 'ووٹرز سروس پورٹل پر یا اپنے BLO کے ذریعے فارم 8 (رہائش کی منتقلی) سے درخواست دیں۔',
        },
      ],
      fees: [{ id: 'voter-form-8-shifting-fee', label: FREE, amountInr: 0, meta: meta(CONTENT) }],
      sources: ['voters-service-portal'],
      priority: 41,
      history,
      meta: meta(CONTENT),
    },
  ],
  placeVariants: {
    meta: meta(CONTENT, { source: 'Officially renamed places (Karnataka city renaming, 1 November 2014; Mumbai, Chennai, Kolkata) — to be verified (O03)' }),
    groups: [
      { canonical: 'bengaluru', variants: ['bengaluru', 'bangalore', 'banglore', 'bengalooru'] },
      { canonical: 'mysuru', variants: ['mysuru', 'mysore'] },
      { canonical: 'mangaluru', variants: ['mangaluru', 'mangalore'] },
      { canonical: 'belagavi', variants: ['belagavi', 'belgaum'] },
      { canonical: 'kalaburagi', variants: ['kalaburagi', 'gulbarga'] },
      { canonical: 'ballari', variants: ['ballari', 'bellary'] },
      { canonical: 'hubballi', variants: ['hubballi', 'hubli'] },
      { canonical: 'vijayapura', variants: ['vijayapura', 'bijapur'] },
      { canonical: 'shivamogga', variants: ['shivamogga', 'shimoga'] },
      { canonical: 'tumakuru', variants: ['tumakuru', 'tumkur'] },
      { canonical: 'chikkamagaluru', variants: ['chikkamagaluru', 'chikmagalur'] },
      { canonical: 'mumbai', variants: ['mumbai', 'bombay'] },
      { canonical: 'chennai', variants: ['chennai', 'madras'] },
      { canonical: 'kolkata', variants: ['kolkata', 'calcutta'] },
    ],
  },
  addressAbbreviations: {
    meta: meta(CONTENT, { source: 'Common Indian address abbreviations — maintained by the content team' }),
    entries: [
      { short: 'rd', long: 'road' },
      { short: 'st', long: 'street' },
      { short: 'ln', long: 'lane' },
      { short: 'crs', long: 'cross' },
      { short: 'mn', long: 'main' },
      { short: 'nr', long: 'near' },
      { short: 'opp', long: 'opposite' },
      { short: 'apt', long: 'apartment' },
      { short: 'apts', long: 'apartments' },
      { short: 'bldg', long: 'building' },
      { short: 'flr', long: 'floor' },
      { short: 'blk', long: 'block' },
      { short: 'ext', long: 'extension' },
      { short: 'ngr', long: 'nagar' },
    ],
    ignore: ['no', 'hno', 'dno'],
  },
  servicePrices: [],
};
