/** Embeds drizzle/*.sql into src/migrations.generated.ts so migrations run inside any bundle (ADR-011). */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const files = readdirSync(join(root, 'drizzle')).filter((f) => f.endsWith('.sql')).sort();
const migrations = files.map((f) => ({ id: f.replace(/\.sql$/, ''), sql: readFileSync(join(root, 'drizzle', f), 'utf8') }));
writeFileSync(
  join(root, 'src/migrations.generated.ts'),
  `/* Generated by scripts/embed-migrations.ts from drizzle/*.sql — do not edit. */\nexport const MIGRATIONS: { id: string; sql: string }[] = ${JSON.stringify(migrations, null, 2)};\n`,
);
console.log(`Embedded ${migrations.length} migrations: ${migrations.map((m) => m.id).join(', ')}`);
