/**
 * F12-AC-3.x · Traceability: which acceptance criteria and examples each spec defines,
 * and which tests reference them by ID.
 */
import { acceptanceCriteria, examples, functionalRequirements, type SpecFile } from './spec/specs';

/** Specs at or past Gate 1: every acceptance criterion must have a test (F12-AC-3.2). */
export const BLOCKING_STATUSES = ['Approved', 'Planned', 'In build', 'Verified', 'Released'];

export const TEST_ID = /\b([FMDXO]\d{2}-(?:AC-\d+\.\d+|EX-[a-z0-9]+(?:-[a-z0-9]+)*))\b/g;

export interface TestFile {
  path: string;
  text: string;
}

export interface SpecTrace {
  id: string;
  dir: string;
  status: string;
  version: string;
  blocking: boolean;
  frCount: number;
  criteria: { id: string; tests: string[] }[];
  examples: { id: string; tests: string[] }[];
}

export interface TraceResult {
  specs: SpecTrace[];
  unknownReferences: { id: string; where: string }[];
  failures: string[];
}

export function buildTrace(specs: Pick<SpecFile, 'id' | 'dir' | 'status' | 'version' | 'text'>[], tests: TestFile[]): TraceResult {
  const references = new Map<string, Set<string>>();
  for (const file of tests) {
    file.text.split('\n').forEach((line, i) => {
      for (const m of line.matchAll(TEST_ID)) {
        const set = references.get(m[1]!) ?? new Set<string>();
        set.add(`${file.path}:${i + 1}`);
        references.set(m[1]!, set);
      }
    });
  }

  const known = new Set<string>();
  const traces: SpecTrace[] = specs.map((spec) => {
    const acs = acceptanceCriteria(spec.text);
    const exs = [...examples(spec.text).keys()];
    [...acs, ...exs].forEach((id) => known.add(id));
    return {
      id: spec.id,
      dir: spec.dir,
      status: spec.status,
      version: spec.version,
      blocking: BLOCKING_STATUSES.includes(spec.status),
      frCount: functionalRequirements(spec.text).length,
      criteria: acs.map((id) => ({ id, tests: [...(references.get(id) ?? [])] })),
      examples: exs.map((id) => ({ id, tests: [...(references.get(id) ?? [])] })),
    };
  });

  const unknownReferences = [...references.entries()]
    .filter(([id]) => !known.has(id))
    .flatMap(([id, where]) => [...where].map((w) => ({ id, where: w })));

  const failures = [
    ...traces.flatMap((s) =>
      s.blocking ? s.criteria.filter((c) => c.tests.length === 0).map((c) => `${c.id} (spec ${s.id} is ${s.status}) has no test`) : [],
    ),
    ...unknownReferences.map((u) => `${u.where} references ${u.id}, which no spec defines`),
  ];

  return { specs: traces, unknownReferences, failures };
}

export function renderTrace(result: TraceResult): string {
  const lines: string[] = [];
  const totalAc = result.specs.reduce((n, s) => n + s.criteria.length, 0);
  const coveredAc = result.specs.reduce((n, s) => n + s.criteria.filter((c) => c.tests.length).length, 0);
  const totalEx = result.specs.reduce((n, s) => n + s.examples.length, 0);
  const coveredEx = result.specs.reduce((n, s) => n + s.examples.filter((e) => e.tests.length).length, 0);

  lines.push('# Traceability report', '');
  lines.push('Generated by `npm run trace` from `specs/*/spec.md` and the test files. Do not edit by hand.', '');
  lines.push(`- Acceptance criteria with tests: **${coveredAc} / ${totalAc}**`);
  lines.push(`- Executable examples with tests: **${coveredEx} / ${totalEx}**`);
  lines.push(`- Blocking failures: **${result.failures.length}**`, '');
  lines.push('| Spec | Status | Version | FRs | ACs tested | Examples tested |', '|---|---|---|---|---|---|');
  for (const s of result.specs) {
    const ac = `${s.criteria.filter((c) => c.tests.length).length} / ${s.criteria.length}`;
    const ex = `${s.examples.filter((e) => e.tests.length).length} / ${s.examples.length}`;
    lines.push(`| [${s.id}](../specs/${s.dir}/spec.md) | ${s.status} | ${s.version} | ${s.frCount} | ${ac} | ${ex} |`);
  }
  for (const s of result.specs) {
    lines.push('', `## ${s.id} · ${s.dir.replace(/^[A-Z]\d{2}-/, '')}`, '');
    lines.push('| ID | Tests |', '|---|---|');
    for (const item of [...s.criteria, ...s.examples]) {
      lines.push(`| ${item.id} | ${item.tests.length ? item.tests.map((t) => `\`${t}\``).join('<br>') : '**none**'} |`);
    }
  }
  if (result.failures.length) {
    lines.push('', '## Failures', '', ...result.failures.map((f) => `- ${f}`));
  }
  return `${lines.join('\n')}\n`;
}
